/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiPages;
import systemData.BookDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AddNewBookPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddNewBookPage.class.getName());

    /**
     * Creates new form AddNewBookPage
     */
    public AddNewBookPage() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        authorField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        copiesField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        submitNewBookBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 93, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Author:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Add New Book");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copies");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Code:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        authorField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(authorField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 260, -1));

        titleField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 260, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter the details of the new book.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        codeField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(codeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 260, -1));

        copiesField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(copiesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 260, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Title:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        submitNewBookBtn.setBackground(new java.awt.Color(153, 255, 102));
        submitNewBookBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        submitNewBookBtn.setForeground(new java.awt.Color(0, 51, 0));
        submitNewBookBtn.setText("Submit");
        submitNewBookBtn.addActionListener(this::submitNewBookBtnActionPerformed);
        jPanel1.add(submitNewBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 260, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 0));
        jButton1.setText("Back");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitNewBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitNewBookBtnActionPerformed
        // TODO add your handling code here:
        // Get input values
        String title = titleField.getText().trim();
        String author = authorField.getText().trim();
        String code = codeField.getText().trim();
        String copiesText = copiesField.getText().trim();

        // Validate empty fields
        if (title.isEmpty() || author.isEmpty() || code.isEmpty() || copiesText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        int copies;

        // Validate number input
        try {
            copies = Integer.parseInt(copiesText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Copies must be a number.");
            return;
        }

        // Ensure books are loaded
        BookDatabase.loadBooks();

        // Call add method
        boolean success = BookDatabase.addBook(title, author, code, copies);

        if (success) {
            JOptionPane.showMessageDialog(this, "Book added successfully.");

            // Optional: clear fields
            titleField.setText("");
            authorField.setText("");
            codeField.setText("");
            copiesField.setText("");

        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to add book.\nCheck inputs or duplicate code.");
        }
        
        BookManagementPage page = new BookManagementPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_submitNewBookBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AddNewBookPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField authorField;
    private javax.swing.JTextField codeField;
    private javax.swing.JTextField copiesField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitNewBookBtn;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
