/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiPages;
import systemData.BookDatabase;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BookManagementPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BookManagementPage.class.getName());

    /**
     * Creates new form BookManagementPage
     */
    public BookManagementPage() {
        initComponents();
        loadBookManagementTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        removeBookBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookManagementTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        addNewBookBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 93, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        removeBookBtn.setBackground(new java.awt.Color(153, 255, 102));
        removeBookBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        removeBookBtn.setForeground(new java.awt.Color(0, 51, 0));
        removeBookBtn.setText("Remove Book/s");
        removeBookBtn.addActionListener(this::removeBookBtnActionPerformed);
        jPanel1.add(removeBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Book");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, 60));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 120)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Management");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List of Books");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        bookManagementTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0)));
        bookManagementTable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bookManagementTable.setForeground(new java.awt.Color(0, 51, 0));
        bookManagementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookManagementTable.setSelectionBackground(new java.awt.Color(0, 51, 0));
        jScrollPane2.setViewportView(bookManagementTable);

        jScrollPane1.setViewportView(jScrollPane2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 1200, 490));

        backBtn.setBackground(new java.awt.Color(153, 255, 102));
        backBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        addNewBookBtn.setBackground(new java.awt.Color(153, 255, 102));
        addNewBookBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        addNewBookBtn.setForeground(new java.awt.Color(0, 51, 0));
        addNewBookBtn.setText("Add New Book");
        addNewBookBtn.addActionListener(this::addNewBookBtnActionPerformed);
        jPanel1.add(addNewBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Trusted by: Cavite State University - Imus Campus");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("© 2026 Library Management System. All rights reserved.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 740, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookBtnActionPerformed
        // TODO add your handling code here:
        RemoveBookPage page = new RemoveBookPage();
        page.setVisible(true);
    }//GEN-LAST:event_removeBookBtnActionPerformed

    private void addNewBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBookBtnActionPerformed
        // TODO add your handling code here:
        AddNewBookPage page = new AddNewBookPage();
        page.setVisible(true);
    }//GEN-LAST:event_addNewBookBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BookManagementPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewBookBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable bookManagementTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeBookBtn;
    // End of variables declaration//GEN-END:variables

    private void loadBookManagementTable() {
        // Load books (prevent empty table)
        BookDatabase.loadBooks();

        // Column headers
        String[] columns = {
            "Title",
            "Author",
            "Code",
            "Copies"
        };

        // Create model
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        // Populate rows
        for (BookDatabase.Book book : BookDatabase.books) {
            Object[] row = {
                book.title,
                book.author,
                book.code,
                book.copies
            };
            model.addRow(row);
        }

        // Attach to JTable
        bookManagementTable.setModel(model);
        }
}
