package guiPages;
import systemData.BookDatabase;
import systemData.SessionData;
import systemData.LogsDatabase;

/**
 *
 * @author Admin
 */
public class CheckoutPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckoutPage.class.getName());

    /**
     * Creates new form CheckoutPage
     */
    public CheckoutPage() {
        initComponents();
        loadSelectedBooks();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        confirmBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(checkoutTable);

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(this::confirmBtnActionPerformed);

        jLabel1.setText("CHECKOUT PAGE");

        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(94, 94, 94)
                        .addComponent(confirmBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // IF THERE IS NO USER LOGGED IN > ERROR MESSAGE
        if (SessionData.currentUser == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Login first");

            new HomePage().setVisible(true);
            this.dispose();
            return;
        }
        
        // IF USER HAVE NO SELECTED BOOKS > ERROR MESSAGE
        if (SessionData.selectedBooks.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No books selected");
            return;
        }
        
        // STORE TO LOGS THAT THE USER HAD CHECKOUT ACTION
        String user = SessionData.currentUser;

        // 🔥 PROCESS EACH SELECTED BOOK
        for (String code : SessionData.selectedBooks) {

            // Find book by code
            for (BookDatabase.Book b : BookDatabase.books) {

                if (b.code.equals(code)) {

                    // ✅ CHECK STOCK (extra safety)
                    if (b.copies <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Book out of stock: " + b.title
                        );
                        return;
                    }

                    // ✅ DECREASE ONLY HERE (FINAL FIX)
                    b.copies--;

                    // ✅ LOG
                    LogsDatabase.addLog(
                            user,
                            "CHECKOUT",
                            b.title
                    );

                    break;
                }
            }
        }

        // Clear session AFTER processing
        SessionData.selectedBooks.clear();

        javax.swing.JOptionPane.showMessageDialog(this, "Checkout Confirmed");

        new FormPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LibraryPage page = new LibraryPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckoutPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadSelectedBooks() {
        // Define columns
        String[] columns = {
            "Book Title",
            "Book Code"
        };

        // Use DefaultTableModel (dynamic, no manual array sizing)
        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(columns, 0);

        // Fill rows
        for (String code : SessionData.selectedBooks) {

            String title = "Unknown";

            // Find title using code
            for (BookDatabase.Book b : BookDatabase.books) {
                if (b.code.equals(code)) {
                    title = b.title;
                    break;
                }
            }

            // Add row (Title first, then Code)
            model.addRow(new Object[]{title, code});
        }

        // Set model to table
        checkoutTable.setModel(model);
    }
}
