package guiPages;
import systemData.BookDatabase;
import systemData.SessionData;
import systemData.LogsDatabase;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class CheckoutPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckoutPage.class.getName());

    /**
     * Creates new form CheckoutPage
     */
    public CheckoutPage() {
        initComponents();
        loadSelectedBooks();
        setLocationRelativeTo(null);
        checkoutTable.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        confirmBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkoutTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0)));
        checkoutTable.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        checkoutTable.setForeground(new java.awt.Color(0, 51, 0));
        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        checkoutTable.setSelectionBackground(new java.awt.Color(0, 51, 0));
        jScrollPane1.setViewportView(checkoutTable);

        confirmBtn.setBackground(new java.awt.Color(153, 255, 102));
        confirmBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        confirmBtn.setForeground(new java.awt.Color(0, 51, 0));
        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(this::confirmBtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("List of Selected Books");

        backBtn.setBackground(new java.awt.Color(153, 255, 102));
        backBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confirmBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // STORE TO LOGS THAT THE USER HAD CHECKOUT ACTION
        String user = SessionData.currentUser;

        // PROCESS EACH SELECTED BOOK
        for (String code : SessionData.selectedBooks) {

            // Find book by code
            for (BookDatabase.Book b : BookDatabase.books) {

                if (b.code.equals(code)) {

                    // CHECK STOCK (extra safety)
                    if (b.copies <= 0) {
                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Book out of stock: " + b.title
                        );
                        return;
                    }

                    // DECREASE ONLY HERE (FINAL FIX)
                    b.copies--;

                    // LOG
                    LogsDatabase.addLog(
                            user,
                            "CHECKOUT",
                            b.title
                    );

                    break;
                }
            }
        }

        // Clear session AFTER processing
        SessionData.selectedBooks.clear();

        JOptionPane.showMessageDialog(this, "Checkout Confirmed.", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        new FormPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        LibraryPage page = new LibraryPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckoutPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadSelectedBooks() {
        // Define columns
        String[] columns = {
            "Book Title",
            "Book Code"
        };

        // Use DefaultTableModel (dynamic, no manual array sizing)
        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(columns, 0);

        // Fill rows
        for (String code : SessionData.selectedBooks) {

            String title = "Unknown";

            // Find title using code
            for (BookDatabase.Book b : BookDatabase.books) {
                if (b.code.equals(code)) {
                    title = b.title;
                    break;
                }
            }

            // Add row (Title first, then Code)
            model.addRow(new Object[]{title, code});
        }

        // Set model to table
        checkoutTable.setModel(model);
    }
}
