package guiPages;
import systemData.SessionData;
import systemData.LogsDatabase;

/**
 *
 * @author Admin
 */
public class CheckoutPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckoutPage.class.getName());

    /**
     * Creates new form CheckoutPage
     */
    public CheckoutPage() {
        initComponents();
        loadSelectedBooks();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        confirmBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(checkoutTable);

        confirmBtn.setText("Confirm");
        confirmBtn.addActionListener(this::confirmBtnActionPerformed);

        jLabel1.setText("CHECKOUT PAGE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmBtn)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmBtn)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBtnActionPerformed
        // IF THERE IS NO USER LOGGED IN > ERROR MESSAGE
        if (SessionData.currentUser == null) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Login first"
            );

            HomePage page = new HomePage();
            page.setVisible(true);
            this.dispose();
            return;
        }
        
        // IF USER HAVE NO SELECTED BOOKS > ERROR MESSAGE
        if (SessionData.selectedBooks.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No books selected"
            );

            return;
        }
        
        // STORE TO LOGS THAT THE USER HAD CHECKOUT ACTION
        String user = SessionData.currentUser;

        for (String book : SessionData.selectedBooks) {

            LogsDatabase.addLog(
                    user,
                    "CHECKOUT",
                    book
            );
        }
        
        // RESET THE SELECTED BOOKS 
        SessionData.selectedBooks.clear();
        
        // IF USER SUCCESSFULLY CONFIRMED > SUCCESS MESSAGE
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Checkout Confirmed"
        );

        FormPage page = new FormPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CheckoutPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton confirmBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadSelectedBooks() {
        // Define column | table has only 1 column | Header = "Selected Books"
        String[] columns = {
        "Selected Books"
        };
        
        // Create data array | Rows = number of selected books | Columns = 1
        Object[][] data =
                new Object[SessionData.selectedBooks.size()][1];
        
        // Fill the data
        for (int i = 0; i < SessionData.selectedBooks.size(); i++) {

            data[i][0] = SessionData.selectedBooks.get(i);

        }
        
        // Create table model | This connects: data + columns → JTable model
        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                        data,
                        columns
                );

        checkoutTable.setModel(model);
    }
}
