// import packages
package guiPages;
import systemData.BookDatabase;
import systemData.SessionData;
import javax.swing.JOptionPane;

public class LibraryPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibraryPage.class.getName());

    public LibraryPage() {
        initComponents();
        BookDatabase.loadBooks(); // load books from BookDatabase using loadBooks() method
        loadTable(); // load books in table using loadTable() method
        setLocationRelativeTo(null); // set the GUI to the center of the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        checkoutBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 93, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("CvSU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, 60));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Our Collection");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 120)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setText("LIBRARY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, -1, -1));

        back.setBackground(new java.awt.Color(153, 255, 102));
        back.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 51, 0));
        back.setText("Back");
        back.addActionListener(this::backActionPerformed);
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Management");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        checkoutBtn.setBackground(new java.awt.Color(153, 255, 102));
        checkoutBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(0, 51, 0));
        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(this::checkoutBtnActionPerformed);
        jPanel1.add(checkoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 190, -1, -1));

        bookTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0)));
        bookTable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        bookTable.setForeground(new java.awt.Color(0, 51, 0));
        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        bookTable.setGridColor(new java.awt.Color(255, 255, 255));
        bookTable.setSelectionBackground(new java.awt.Color(0, 51, 0));
        bookTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(bookTable);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 1260, 490));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Trusted by: Cavite State University - Imus Campus");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2026 Library Management System. All rights reserved.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 740, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\cvsu.png")); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\book.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 40, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\books 40px.png")); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 40, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\cart.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 180, 40, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        SessionData.selectedBooks.clear(); // clear previous session | prevents old selections from staying | ensures fresh checkout
        
        // get table model from the varible name of jTable
        javax.swing.table.TableModel model = bookTable.getModel();
        int count = 0; // tracks how many books will be checked by the user
        
        // send a confirmation button before checking out
        int userChoice = javax.swing.JOptionPane.showConfirmDialog(this, "Proceed to checkout?", "Confirmation", javax.swing.JOptionPane.YES_NO_OPTION);
        
        // if user select yes then run this code
        if (userChoice == javax.swing.JOptionPane.YES_OPTION){
            // Loop through all rows | You check every row in the table.
            for (int i = 0; i < model.getRowCount(); i++) {

                Boolean selected = (Boolean) model.getValueAt(i, 4); // last column checkboxes | will check if checkboxes are being checked
                if (selected != null && selected) { // Only proceed if user checked the checkboxes

                    // Prevent selecting out-of-stock
                    Object copiesObj = model.getValueAt(i, 3);
                    if (copiesObj.toString().equals("OUT OF STOCK")) {
                        JOptionPane.showMessageDialog(this, "Book out of stock.", "No book was found", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    // User can only borrow up to 5 books at a time | so if they selected more than 5 > send warning message
                    count++; // this will track how many books are being checked
                    if (count > 5) {
                        JOptionPane.showMessageDialog(this, "Only up to 5 books allowed at a time.", "Limitation", javax.swing.JOptionPane.WARNING_MESSAGE);
                        return;
                    }

                    // Get the book code to identify the book
                    String code = model.getValueAt(i, 2).toString();
                    SessionData.selectedBooks.add(code); // then store the selected books to SessionData.selectedBooks() method
                }
            }

            // If there is no checked books > Prevent empty checkout > send error message
            if (count == 0) {
                JOptionPane.showMessageDialog(this, "No book/s selected.\nSelect at least 1.", "No book was found", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Clear checkboxes after checkout
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(false, i, 4);
            }

            // then navigate to CheckoutPage
            CheckoutPage page = new CheckoutPage();
            page.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // back button > navigate to HomePage
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibraryPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        // define the table columns headers using array
        String[] columns = {"TITLE", "AUTHOR", "CODE", "COPIES", "SELECT"};
        
        // create table data using 2d array | rows = number of books and columns = 5 headers
        Object[][] data = new Object[BookDatabase.books.size()][5];
        
        // loop through books | we will get each book from the BookDatabase | b represents one book
        for (int i = 0; i < BookDatabase.books.size(); i++) {
            BookDatabase.Book b = BookDatabase.books.get(i);
            
            // fill the column rows
            data[i][0] = b.title;
            data[i][1] = b.author;
            data[i][2] = b.code;
            
            // handle stock | if no copies then we will display OUT OF STOCK and the checkbox will be disabled
            if (b.copies == 0) {
                data[i][3] = "OUT OF STOCK";
                data[i][4] = null; // checkbox will be disabled
            } else {
                data[i][3] = b.copies;
                data[i][4] = false; // checkbox will be unchecked
            }
        }

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, columns) {
            @Override // exists in DefaultTableModel 
            // column index 4 will be the checkboxes
            public Class getColumnClass(int column) {
                if (column == 4) return Boolean.class;
                return String.class;
            }

            @Override // exists in DefaultTableModel 
            public boolean isCellEditable(int row, int column) {
                if (column != 4) return false; // Only checkbox column is editable
                Object value = getValueAt(row, 3); // Prevent selecting out-of-stock
                
                // If out of stock > cannot click checkbox and we will show OUT OF STOCK
                if (value == null) return false;
                if (value.toString().equals("OUT OF STOCK")) return false; // cannot select OUT OF STOCK
                return true; // otherwise > checkbox is clickable if not OUTO OF STOCK
            }
        };
        // apply model to variable name of the table
        bookTable.setModel(model);
    }
}
