// IMPORT NECESSARY PACKAGES
package guiPages;
import systemData.BookDatabase;
import systemData.SessionData;

public class LibraryPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LibraryPage.class.getName());

    // LOAD BOOK DATABASE AND TABLE
    public LibraryPage() {
        initComponents();
        BookDatabase.loadBooks();
        loadTable();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        checkoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(bookTable);

        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(this::checkoutBtnActionPerformed);

        jLabel1.setText("DASHBOARD/LIBRARY PAGE");

        back.setText("<-- Back");
        back.addActionListener(this::backActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(back)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkoutBtn))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutBtn)
                    .addComponent(back))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        SessionData.selectedBooks.clear(); // Clear previous session | Prevents old selections from staying | Ensures fresh checkout
        
        // Get table model from the varible name of jTable
        javax.swing.table.TableModel model = bookTable.getModel();
        int count = 0; // Tracks how many books selected 
        
        // Loop through all rows | You check every row in the table.
        for (int i = 0; i < model.getRowCount(); i++) {
            
            Boolean selected = (Boolean) model.getValueAt(i, 4); // last column checkbox | will check if checkbox is selected
            if (selected != null && selected) { // Only proceed if user checked it
                
                // Prevent selecting out-of-stock
                Object copiesObj = model.getValueAt(i, 3);
                if (copiesObj.toString().equals("OUT OF STOCK")) { // Extra safety check
                    javax.swing.JOptionPane.showMessageDialog(this, "Book out of stock");
                    return;
                }
                
                // User can only borrow max 3 books | so if they selected more than 3 > error message
                count++;
                if (count > 3) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Only up to 3 books allowed");
                    return;
                }

                // Get book code to identify the book
                String code = model.getValueAt(i, 2).toString();
                SessionData.selectedBooks.add(code);
            }
        }
        
        // If nothing selected > Prevent empty checkout
        if (count == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select at least 1 book");
            return;
        }

        // Clear or reset checkboxes after checkout
        for (int i = 0; i < model.getRowCount(); i++) {
            model.setValueAt(false, i, 4);
        }
        
        // Navigate to CheckoutPage
        CheckoutPage page = new CheckoutPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LibraryPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void loadTable() {
        // DEFINE THE TABLE COLUMNS/HEADERS
        String[] columns = {
            "Title",
            "Author",
            "Code",
            "Copies",
            "Select"   // checkbox at the end
        };
        
        // CREATE TABLE DATA CONTAINER | Rows = number of books and Columns = 5
        Object[][] data = new Object[BookDatabase.books.size()][5];
        
        // LOOP THROUGH BOOKS | WE WILL GET EACH BOOK FROM BOOK DATABASE | b represents one book
        for (int i = 0; i < BookDatabase.books.size(); i++) {
            BookDatabase.Book b = BookDatabase.books.get(i);
            
            // FILL COLUMNS
            data[i][0] = b.title;
            data[i][1] = b.author;
            data[i][2] = b.code;
            
            // HANDLE STOCK LOGIC | IF NO COPIES THEN WILL SHOW OUT OF STOCK AND THE CHECKBOX WILL BE DISABLED
            if (b.copies == 0) {
                data[i][3] = "OUT OF STOCK";
                data[i][4] = null; // checkbox disabled
            } else {
                data[i][3] = b.copies;
                data[i][4] = false; // checkbox unchecked
            }
        }

        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, columns) {
            @Override // COLUMN 4 BECOMES A CHECKBOX COLUMN
            public Class getColumnClass(int column) {
                if (column == 4) return Boolean.class; // last column is checkbox
                return String.class;
            }

            @Override // CHECKBOX CONTROL 
            public boolean isCellEditable(int row, int column) {
                if (column != 4) return false; // Only checkbox column is editable
                Object value = getValueAt(row, 3); // Prevent selecting out-of-stock
                // If out of stock > cannot click checkbox and we will show OUT OF STOCK
                if (value == null) return false;
                if (value.toString().equals("OUT OF STOCK")) return false; // cannot select out-of-stock
                return true; // Otherwise > checkbox is clickable
            }
        };
        // APPLY MODEL TO TABLE
        bookTable.setModel(model);
    }
}
