// import packages
package guiPages;
import systemData.UserDatabase;
import systemData.SessionData;
import systemData.LogsDatabase;
import javax.swing.JOptionPane;

public class LogInPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogInPage.class.getName());

    public LogInPage() {
        initComponents();
        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
        progressBar.setValue(0);
        progressBar.setStringPainted(true);
        progressBar.setVisible(false);
        setLocationRelativeTo(null); // set the GUI to the center of the screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        registerNowBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 93, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Log In Account");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 50));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("@CvSU Library Management System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 210, -1));

        usernameField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 240, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        passwordField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 240, -1));

        loginBtn.setBackground(new java.awt.Color(153, 255, 102));
        loginBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(0, 51, 0));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(this::loginBtnActionPerformed);
        jPanel1.add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 240, -1));

        backBtn.setBackground(new java.awt.Color(153, 255, 102));
        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 23, 60, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter your information to log in your account.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        registerNowBtn.setBackground(new java.awt.Color(153, 255, 102));
        registerNowBtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        registerNowBtn.setForeground(new java.awt.Color(0, 51, 0));
        registerNowBtn.setText("Don’t have an account? Register now!");
        registerNowBtn.addActionListener(this::registerNowBtnActionPerformed);
        jPanel1.add(registerNowBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 240, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome to CvSU Library!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\cvsu stroke.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\books 40px.png")); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        progressBar.setBackground(new java.awt.Color(204, 204, 204));
        progressBar.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        progressBar.setForeground(new java.awt.Color(0, 51, 0));
        jPanel1.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 240, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // // create variables to get username and password 
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword());
        
        // LogInPage Validations/Authentication
        // if username and password is empty > send warning message
        if (username.isEmpty() || password.isEmpty()) {

            JOptionPane.showMessageDialog(this, "All fields are required", "Authentication Failed", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Disable login button to prevent multiple clicks
        loginBtn.setEnabled(false);

        // Show progress bar
        progressBar.setVisible(true);
        progressBar.setValue(0);

        // Timer for loading effect
        javax.swing.Timer timer = new javax.swing.Timer(15, null);

        timer.addActionListener(new java.awt.event.ActionListener() {
            int progress = 0;

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                progress++;
                progressBar.setValue(progress);

                if (progress >= 100) {
                    timer.stop();

                    // create a variable to valid username and password from the UserDatabase
                    boolean valid = UserDatabase.validate(username, password);

                    if (valid) {

                        // logged in user
                        SessionData.currentUser = username;

                        // store the username action to LogsDatabase addLog() method
                        LogsDatabase.addLog(
                                username,
                                "LOGIN",
                                "-"
                        );

                        // if username and password is valid from the UserDatabase > send success message
                        javax.swing.JOptionPane.showMessageDialog(null, "Log in successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

                        // navigate to HomePage
                        HomePage page = new HomePage();
                        page.setVisible(true);
                        dispose();

                    } else {
                        // else if username and password is not valid > send warning message
                        JOptionPane.showMessageDialog(null, "Invalid username or password.", "Authentication Failed", javax.swing.JOptionPane.WARNING_MESSAGE);
                    }

                    // Reset UI
                    progressBar.setVisible(false);
                    loginBtn.setEnabled(true);
                }
            }
        });

        timer.start();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // back button > navigate to HomePage
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void registerNowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNowBtnActionPerformed
        // register now button > navigate to SignUpPage
        SignUpPage page = new SignUpPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerNowBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogInPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton registerNowBtn;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
