/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guiPages;
import systemData.LogsDatabase;
/**
 *
 * @author Admin
 */
public class LogsPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LogsPage.class.getName());

    /**
     * Creates new form LogsPage
     */
    public LogsPage() {
        initComponents();
        loadLogs();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        registeredStudentsBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        logsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(58, 93, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(153, 255, 102));
        backBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        jPanel1.add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Logs");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        registeredStudentsBtn.setBackground(new java.awt.Color(153, 255, 102));
        registeredStudentsBtn.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        registeredStudentsBtn.setForeground(new java.awt.Color(0, 51, 0));
        registeredStudentsBtn.setText("List of Registered Users");
        registeredStudentsBtn.addActionListener(this::registeredStudentsBtnActionPerformed);
        jPanel1.add(registeredStudentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("CvSU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, 60));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 204));
        jLabel4.setText("Management");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 100)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("LIBRARY");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        logsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 0)));
        logsTable.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        logsTable.setForeground(new java.awt.Color(0, 51, 0));
        logsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        logsTable.setSelectionBackground(new java.awt.Color(0, 51, 0));
        jScrollPane1.setViewportView(logsTable);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 1220, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void registeredStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredStudentsBtnActionPerformed
        // TODO add your handling code here:
        RegisteredPage page = new RegisteredPage();
        page.setVisible(true);
    }//GEN-LAST:event_registeredStudentsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LogsPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable logsTable;
    private javax.swing.JButton registeredStudentsBtn;
    // End of variables declaration//GEN-END:variables

    private void loadLogs() {
        // DEFINE TABLE COLUMNS
        String[] columns = {
            "Username",
            "Action",
            "Book",
            "Date"
        };
        
        // CREATE DATA CONTAINER | Rows = number of logs | Columns = 4
        Object[][] data =
                new Object[LogsDatabase.logs.size()][4];
        
        // LOOP THROUGH LOGS | iterate through all stored logs.
        for (int i = 0; i < LogsDatabase.logs.size(); i++) {
            
            // Get each log object 
            LogsDatabase.Log log =
                    LogsDatabase.logs.get(i);
            
            // Each log contains: username, action, bookTitle, and date
            data[i][0] = log.username;
            data[i][1] = log.action;
            data[i][2] = log.bookTitle;
            data[i][3] = log.date;
        }
        
        // CREATE THE TABLE MODEL
        javax.swing.table.DefaultTableModel model =
                new javax.swing.table.DefaultTableModel(
                        data,
                        columns
                );
        
        // SET MODEL TO TABLE
        logsTable.setModel(model);
    }
}
