package guiPages;
import systemData.BookDatabase;
import systemData.SessionData;
import systemData.LogsDatabase;
import javax.swing.JOptionPane;
import systemData.UserBorrowedBooksDatabase;

/**
 *
 * @author Admin
 */
public class ReturnBookPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReturnBookPage.class.getName());

    /**
     * Creates new form ReturnBookPage
     */
    public ReturnBookPage() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        codeField1 = new javax.swing.JTextField();
        codeField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codeField3 = new javax.swing.JTextField();
        codeField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codeField5 = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(153, 255, 102));
        backBtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 14, -1, -1));

        jPanel1.setBackground(new java.awt.Color(58, 93, 46));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Thank you for borrowing! @CvSU Library!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        codeField1.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        codeField1.addActionListener(this::codeField1ActionPerformed);
        jPanel1.add(codeField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 200, -1));
        jPanel1.add(codeField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 200, -1));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 31)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return a Book");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("4.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter the book code to return the book.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("1.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("2.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel1.add(codeField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 200, -1));
        jPanel1.add(codeField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 200, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("3.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("5.");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));
        jPanel1.add(codeField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 200, -1));

        submitBtn.setBackground(new java.awt.Color(153, 255, 102));
        submitBtn.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(0, 51, 0));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(this::submitBtnActionPerformed);
        jPanel1.add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 260, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("This will process book return.");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\cvsu stroke.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        int userChoice = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to return the selected books?",
            "Return Book Confirmation",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (userChoice == javax.swing.JOptionPane.YES_OPTION) {

            String[] codes = {
                codeField1.getText().trim(),
                codeField2.getText().trim(),
                codeField3.getText().trim(),
                codeField4.getText().trim(),
                codeField5.getText().trim()
            };

            int returned = 0;
            int totalEntered = 0;

            // TEMP STORAGE (for atomic operation)
            java.util.ArrayList<UserBorrowedBooksDatabase> recordsToReturn = new java.util.ArrayList<>();

            // =========================
            // PHASE 1: VALIDATION ONLY
            // =========================
            for (String code : codes) {

                if (code.isEmpty()) continue;

                totalEntered++;

                UserBorrowedBooksDatabase recordToRemove = null;

                // Check if user actually borrowed this book
                for (UserBorrowedBooksDatabase record : SessionData.borrowedBooks) {
                    if (record.username.equals(SessionData.currentUser)
                            && record.code.equalsIgnoreCase(code)) {

                        recordToRemove = record;
                        break;
                    }
                }

                // If invalid → STOP EVERYTHING
                if (recordToRemove == null) {
                    JOptionPane.showMessageDialog(
                            this,
                            "You can only return books that you have borrowed.\nPlease double check the book codes.",
                            "Invalid Book Code",
                            javax.swing.JOptionPane.WARNING_MESSAGE
                    );
                    return;
                }

                // Store valid record for execution phase
                recordsToReturn.add(recordToRemove);
            }

            // IF NO USER INPUT
            if (totalEntered == 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Please enter at least one book code.",
                        "Returning Book Failed",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // =========================
            // PHASE 2: EXECUTION
            // =========================
            for (UserBorrowedBooksDatabase record : recordsToReturn) {

                for (BookDatabase.Book b : BookDatabase.books) {
                    if (b.code.equalsIgnoreCase(record.code)) {

                        b.copies++;

                        LogsDatabase.addLog(
                                SessionData.currentUser,
                                "RETURN",
                                b.title
                        );

                        returned++;
                        break;
                    }
                }

                // Remove from borrowed records
                SessionData.borrowedBooks.remove(record);
            }

            // SUCCESS MESSAGE
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Returned: " + returned,
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            new HomePage().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void codeField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ReturnBookPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField codeField1;
    private javax.swing.JTextField codeField2;
    private javax.swing.JTextField codeField3;
    private javax.swing.JTextField codeField4;
    private javax.swing.JTextField codeField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
