// import packages
package guiPages;
import systemData.UserDatabase;
import javax.swing.JOptionPane;
import java.util.Locale; // for email | converts everything to lowercase in a consistent way

public class SignUpPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpPage.class.getName());

    public SignUpPage() {
        initComponents();
        setLocationRelativeTo(null); // set the GUI to center of the screen 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        usernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentCourse = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        studentIdField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backBtn.setBackground(new java.awt.Color(153, 255, 102));
        backBtn.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        backBtn.setForeground(new java.awt.Color(0, 51, 0));
        backBtn.setText("Back");
        backBtn.addActionListener(this::backBtnActionPerformed);
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 21, -1, -1));

        jPanel2.setBackground(new java.awt.Color(58, 93, 46));
        jPanel2.setForeground(new java.awt.Color(58, 93, 46));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 250, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Course:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        emailField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 250, -1));

        passwordField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 250, -1));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student ID:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        confirmPasswordField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        confirmPasswordField.addActionListener(this::confirmPasswordFieldActionPerformed);
        jPanel2.add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 250, -1));

        jButton1.setBackground(new java.awt.Color(153, 255, 102));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 0));
        jButton1.setText("REGISTER NOW!");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 250, -1));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Create Account");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Username:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fill your information below to register new account.");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("By clicking register now, you agree to CvSU's ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        studentCourse.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        studentCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select...", "BSCS", "BSIT", "BSBA", "BSHM", "BENT", "BAJOURN", "BSPSYCH", "BSOA", "BSED" }));
        jPanel2.add(studentCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 250, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CvSU Email:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        studentIdField.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jPanel2.add(studentIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 250, -1));

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Confirm Password:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\ComProg\\librarySystem\\src\\main\\java\\resources\\cvsu stroke.png")); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jButton2.setBackground(new java.awt.Color(153, 255, 102));
        jButton2.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 0));
        jButton2.setText("User Agreement & Privacy Policy");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 210, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // create variable to get username, email, password, confirm password, course, and student id 
        String username = usernameField.getText().trim();
        String email = emailField.getText().trim().toLowerCase(Locale.ROOT);
        String password = new String(passwordField.getPassword());
        String confirm = new String(confirmPasswordField.getPassword());
        String course = new String(studentCourse.getSelectedItem().toString());
        String studentIdText = studentIdField.getText().trim();
        
        // SignUpPage Validations
        // if username or email or passwrod or student id is empty > send warning message
        if (username.isEmpty() || email.isEmpty() || password.isEmpty() || studentIdText.isEmpty()) {

            JOptionPane.showMessageDialog(this, "All fields are required!", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // if username length is less than 3 or greater than 20 > send warning message
        if (username.length() < 3 || username.length() > 20) {

            JOptionPane.showMessageDialog(this, "Username must be 3–20 characters.", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // if some of the username characters is not an alphabet > send warning message
        if(!username.matches("[a-zA-Z]+")){
            JOptionPane.showMessageDialog(this, "Username must contain letters only.", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // if email length is less than 3 or greater than 32 > send warning message
        if (email.length() < 3 || email.length() > 32 || !email.endsWith("@cvsu.edu.ph")) {

            JOptionPane.showMessageDialog(this, "Invalid format. Email must be @cvsu.edu.ph", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // if student course is not selected (index 0) > send warning message
        if(studentCourse.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this, "Please select your course.", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // if student id is not equal to 9 or greater than 9 > send warning message
        if(studentIdText.length() !=9){
            JOptionPane.showMessageDialog(this, "Please enter a valid student ID.", "Invalid ID format.", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // check if numeric
        if (!studentIdText.matches("\\d+")) { JOptionPane.showMessageDialog(this, "Student ID must contain only numbers.", "Invalid ID format.", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // convert student id to integer
        int studentId = Integer.parseInt(studentIdText);
        
        // if password length is less than 5 or greater than 20 > send warning message
        if (password.length() < 5 || password.length() > 20) {

            JOptionPane.showMessageDialog(this, "Please use a strong password.", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // if password is not equal to confirm password > send warning message
        if(!password.equals(confirm)){
            
            JOptionPane.showMessageDialog(this, "Confirm password did not match.", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        // this will check if there's a duplicate username
        for (UserDatabase.User u : UserDatabase.users) {
            
            // if username is equal to already existing username > send warning message
            if (u.username.equals(username)) {

                JOptionPane.showMessageDialog(this, "Username already exist.\n Please enter a new name.", "Sign Up Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        // after all validation > store username, email, password, course, and student id to the UserDatabase
        UserDatabase.addUser(username, email, password, course, studentId);
        
        // then send a success messsage
        javax.swing.JOptionPane.showMessageDialog(this, "Registered Successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        // navigate to LogInPage
        LogInPage page = new LogInPage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void confirmPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // navigate to HomePage
        HomePage page = new HomePage();
        page.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUpPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> studentCourse;
    private javax.swing.JTextField studentIdField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
